### ISSUE TITLE
You can't make Groups within Groups eventually

### ISSUE THREAD

**Issue by TrizekYT** [mat1jaczyyy/apollo-studio#4]
**Describe the bug**
you can't make groups within groups eventually

**To Reproduce**
create groups within groups

**Expected behavior**
I expected the window to keep going 

**Screenshots**
![epic](https://user-images.githubusercontent.com/45077321/48572689-17856c00-e8d8-11e8-8785-b5cb0a6fdfdb.PNG)

**Your setup**
Windows 10

**Additional context**
it is a big issue and I think scrolling down needs to be an option

**Comment by mat1jaczyyy** [comment]
uhh im not sure abt that @vaaski. also you seem to not know how github issues work, don't go around closing and unlabeling shit in the future

**Comment by mat1jaczyyy** [comment]
@vaaski I believe the inner chain shouldn't scale at all. it should keep the same height, like Ableton's do. If we make them any smaller, we are at some point imposing a normal functionality limit

**Comment by vaaski** [comment]
but i fixed the problem on my side, i closed this issue and was about to make a new one for your api dying

**Comment by mat1jaczyyy** [comment]
@vaaski problem isn't fully fixed on your side. btw can stop acting like a kid pls?

**Comment by vaaski** [comment]
woah o-kay
